### PR TITLE
Replace Rakefile with Makefile

### PR DESCRIPTION
**Pull request by carlosdp**
I love Ruby, but it would be awesome if we didn't add such a dependency when the only time it is used is for a utility script. GNU Make is inherently needed to install ffmpeg anyways, so why not use that to build/install/run tv.js instead?

This PR replaces the Rakefile with the Makefile and updates the README to reflect the changes.

### CODE REVIEW

**Comment by AaronO** [comment]
I agree that it would be a good idea to reduce the dependencies by switching to a Makefile.

Installing yapp.js (install a global npm package) is different depending on the OS, on mac in most cases doesn't require any extra permissions whereas on linux it does require root/sudo permissions.

Check out 5d31ff93b98c4ef3962f4b7447b841856d0cb302 , and adapt your Makefile accordingly if possible (a swtich case on the output of `uname` should do).

**Comment by carlosdp** [comment]
Alright, that should work. I added a uname check for Mac, didn't see the need to check for other OSs since the result would be the same with the exception of Mac.

Let me know if you need something else changed.

**Comment by max-mapper** [comment]
it's a bad idea to require people to `npm install -g` dependencies. if you add yapp.js to your dependencies then when npm installs it you can use an npm script in package.json to launch it without requiring it to be global: https://npmjs.org/doc/scripts.html#path

here's an example: https://github.com/maxogden/requirebin/blob/master/package.json#L5-L8
`browserify` and `beefy` are installed locally, not globally, but NPM knows how to run them as if they were globally installed in the defined `scripts`

**Comment by AaronO** [comment]
@maxogden You are right, since this could also cause version conflicts in the future between the yapp,js version needed to build tv.js and the one a user globally installed for other projects.

Doing so would have the extra benefit of no longer needing sudo permissions on linux (thus removing the necessity for OS checks).

I'm all for it.

@maxogden You're free to submit a pull request for that if you want. I think it would be best to submit a pull request switching over to a local install of yapp.js and adding a `scripts` to the `package.json` and updating the current `Rakefile`.

And then @carlosdp could port these modifications over to his Rakefile -> Makefile pull request.

**Comment by carlosdp** [comment]
Yea sounds good, I'll make those changes to the Makefile in here.

**Comment by carlosdp** [comment]
Alright, the changes assume that YAPP is a devDependency in the package and that a script exists in `package.json` called `build` . It checks that yapp is installed before building, just as before, only locally this time.

**Comment by AaronO** [comment]
Unfortunately @SamyPesse couldn't get your Makefile to work, so he committed a working version with 6e1940e4f0e27acd4f5cdba312a8f1b88fbf1da4.

He should have contributed by commenting here, unfortunately he didn't, which he's sorry about.

Take a look at the current Makefile in the master and I'll be happy to approve a pull request for modifications to it.

Unfortunately it looks like Samy's 6e1940e4f0e27acd4f5cdba312a8f1b88fbf1da4 commit renders this pull request obsolete.

**Comment by carlosdp** [comment]
Ok, that's fine =P

**Pull request closed without merging**
